language: go

go:
- tip
- 1.6.3
- 1.6.2
- 1.6.1
- 1.6
- 1.5.4
- 1.5.3
- 1.5.2
- 1.5.1
- 1.5
- 1.4.3
- 1.4.2
- 1.4.1
- 1.4

os:
- linux
- osx

env:
- GIMME_ARCH=amd64
- GIMME_ARCH=386

matrix:
  exclude:
  - go: 1.4.3
    env: GIMME_ARCH=386

  - go: 1.4.2
    env: GIMME_ARCH=386

  - go: 1.4.1
    env: GIMME_ARCH=386

  - go: 1.4
    env: GIMME_ARCH=386

script:
- go version
- go env
- go build -v ./netmutex
- if [[ "$GOARCH" == "amd64" ]]; then go test -v -race ./netmutex; else go test -v ./netmutex; fi
