language: go

go: 
- tip
- 1.6.3
- 1.6.2
- 1.6.1
- 1.6
- 1.5.4
- 1.5.3
- 1.5.2
- 1.5.1
- 1.5
- 1.4.3
- 1.4.2
- 1.4.1
- 1.4

os:
  - linux
  - osx

script:
- diff -u <(echo -n) <(gofmt -d -s ./netmutex)
- go build -v ./netmutex
- go test -v ./netmutex
- go vet ./netmutex
