language: go

go: 
 - auto
 - tip
 - 1.6.3
 - 1.6.2
 - 1.6.1
 - 1.6
 - 1.5.4
 - 1.5.3
 - 1.5.2
 - 1.5.1
 - 1.5
 - 1.4.3
 - 1.4.2
 - 1.4.1
 - 1.4

env:
 - GIMME_OS=linux GIMME_ARCH=amd64
 - GIMME_OS=linux GIMME_ARCH=386
 - GIMME_OS=linux GIMME_ARCH=arm
 - GIMME_OS=freebsd GIMME_ARCH=amd64
 - GIMME_OS=freebsd GIMME_ARCH=386
 - GIMME_OS=darwin GIMME_ARCH=amd64
 - GIMME_OS=windows GIMME_ARCH=amd64
 - GIMME_OS=windows GIMME_ARCH=386

script:
- go test -v ./netmutex
